language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
cache: pip
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - git clone --depth=1 -b jinja2 https://github.com/f-koehler/dotfiles.git ~/.dotfiles
script:
  - dotgen configs
  - dotgen templates
  - dotgen generate --force default
  - dotgen plugins default
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install PyInstaller; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pyinstaller --hidden-import dotgen.plugins --name dotgen --onefile dotgen/__main__.py; fi
deploy:
  provider: pypi
  user: f-koehler
  password:
    secure: ULvmDYyLPlJQMNg2a6ynD3qzQqEB0pUclIU6qR8OGmsVb3th2q8JFI78l8J1gNgWsBuLLw1HgC4qKDVegzdf21tdATeuhbUwCCHVFEEPZnBLNsHvfzVbQSts6mfzrVLGKRH8/AjWkGhzuLyHq7eR0VmQWVGb3l1NxfAOWjpZfjoiZcEmwq6Nzqbyi0hB4B3AZ4bjRBv0vINQ8xiFuih/AbFBlhPV1sFYPfjqShyLoFljmrgdPoJfYagjeBo/rcABJbiG45tzuIBErJVnGLEZLItIJzqsNfXyTcyD27wnVqoX5kzfHmlhWH4fZbs6XDPZwZ6eeExyITgXTKiyTa/ccVh3o1WDGUn3b2xsSi9I8z2oViWeXBYk9D/JRWMZ4an5dBBncaKDYcWIGpHi26vvZ3VghTr+9QBCfkefkCey2R7CSIBNub5+FAJOH6ELwjcSbvW52Pcs2F2ODSVg0CMCk8jKBYy30d5VX00elH/lopfPb+ECZNBfb+ihg7VOB2mwme15siMMpqnssAcc+JNmmFyJY2m2POSE5oY/tQn4QSw9iMigm/Gne7JA5MuNMbOEMpN2EX6bLSz+OXxAy7YolPJsMud4G10GFsdUpOqOL12GQ6DUxVZDMqrbocAhHmuc7oFfYdfc0DXIb3iQVJhv7mzHKhnBTVc/L1lOBWVNHXs=
  on:
    branch: master
    distributions: sdist
    python: 3.6
    repo: f-koehler/dotgen
    tags: true
