language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypi"
  - "pypi3"
before_script:
  - git clone -b jinja2 https://github.com/f-koehler/dotfiles.git ~/.dotfiles
script:
  - ./dotgen list-configs
  - ./dotgen list-templates
  - ./dotgen preview
  - ./dotgen clear-preview
