language: python
python:
  - "2.7"
  - "3.6"
before_script:
  - git clone -b jinja2 https://github.com/f-koehler/dotfiles.git ~/.dotfiles
script:
  - ./dotgen list-configs
  - ./dotgen list-templates
  - ./dotgen preview
  - ./dotgen clear-preview
